#!groovy

pipeline {

    agent any
    stages {
        stage('Git local config') {
            steps {
                sh 'git config --global --add user.name "example"'
                sh 'git config --global --add user.email "example@example.com"'
            }
        }
        stage('Git clone') {
            steps {
                cleanWs()
                git credentialsId: 'bitbucket-key', url: '$CONFIG_REPO_URL'
            }
        }
        stage('Destroy Prometheus') {
            steps {
                dir("operations/$AWS_REGION/env") {
                    withProxyEnv() {
                        script {
                            sh '''#!/bin/bash -x
                            jx delete addon prometheus
                            kubectl -n jx delete secret prometheus-ingress
                            '''
                        }
                    }
                }
            }
        }
        stage('Read Grafana endpoint') {
            steps {
                dir("operations/$AWS_REGION/env") {
                    withProxyEnv() {
                        script {
                            def jenkinsParameters = readYaml file: 'jenkins/parameters.yaml'
                            def grafanaParameters = readYaml file: 'grafana/parameters.yaml'

                            println "Getting domain name"
                            def r53DomainName = sh(script: "aws route53 get-hosted-zone --id " + jenkinsParameters.jxDomainHostedZoneID + " --output text --query 'HostedZone.Name'", 
                                                   returnStdout: true).trim().replaceAll("\\.\$", "")
                            grafanaEndpoint = "http://grafana.jx." + jenkinsParameters.jxDomainAliasPrefix + "." + r53DomainName
                            grafanaAdminPassword = grafanaParameters.defaultAdminPassword
                        }
                    }
                }
            }
        }
        stage('Destroy Prometheus_ops endpoint in Grafana') {
            steps {
                dir("operations/$AWS_REGION/env") {
                    withProxyEnv() {
                        script {
                            def prometheusDataSourceName = "Prometheus_ops"
                            sh "curl --verbose --user admin:${grafanaAdminPassword} ${grafanaEndpoint}/api/datasources/name/${prometheusDataSourceName} -X DELETE -H 'Content-Type: application/json;charset=UTF-8'"
                        }
                    }
                }
            }
        }
    }
}

void withProxyEnv(List envVars = [], def body) {
    List proxies = []
    List envVaraibles = ['GIT_SSH_COMMAND=ssh -o StrictHostKeyChecking=no']
    withAWSParameterStore(credentialsId: '', namePrefixes: '', naming: 'absolute', path: '/proxy', recursive: true, regionName: "$AWS_REGION") {
        script {
            if (env.PROXY_HTTP) {
                proxies << "http_proxy=$PROXY_HTTP"
            }
            if (env.PROXY_HTTPS) {
                proxies << "https_proxy=$PROXY_HTTPS"
            }
            if (env.PROXY_NO) {
                proxies << "no_proxy=$PROXY_NO"
            }
            envVaraibles.addAll(proxies)
        }
    }
    envVaraibles.addAll(envVars)
    withEnv(envVaraibles) {
        body.call()
    }
}
