pipeline {
    agent any
    stages {

        stage('Assume Cross-account role') {
            steps {
                    withCustomEnv() {
                        sshagent(['bitbucket-key']) {
                        sh '''#!/bin/bash -x
                        assumed_role=$(aws sts assume-role --role-arn ${ROLE_ARN} --role-session-name cross-account-session)
                        export AWS_ACCESS_KEY_ID=$(echo $assumed_role | jq -r .Credentials.AccessKeyId)
                        export AWS_SECRET_ACCESS_KEY=$(echo $assumed_role | jq -r .Credentials.SecretAccessKey)
                        export AWS_SESSION_TOKEN=$(echo $assumed_role | jq -r .Credentials.SessionToken)
                        '''
                        }
                    }
        
            }
        }
        
        stage('check AWS identity') {
            steps {
                    withCustomEnv() {
                        sh '''#!/bin/bash -x
                        aws sts get-caller-identity
                        '''
                    }

            }
        }
        
        stage('Git clone') {
            steps {
                    withCustomEnv() {
                        cleanWs()
                        sshagent(['bitbucket-key']) {
                            sh '''#!/bin/bash -x
                            pwd
                            git clone ${CONFIG_REPO_URL} .
                            ls -al 
                            '''
                        }
                    }
            }
        }

        stage('TF init') {
            steps {
                    withCustomEnv() {
                        sshagent(['bitbucket-key']) {
                            sh '''#!/bin/bash -x
                            pushd ${CONFIG_REPO_DIR}
                            pushd application/${AWS_REGION}/env
                            terraform init \
                                -backend-config=\"region=${AWS_REGION}\" \
                                -backend-config=\"bucket=tf-state-bootstrap-${AWS_APPLICATION_ACCOUNT_NUMBER}-application-${AWS_REGION}\" \
                                -backend-config=\"key=tf/tf-aws-product-domain-${PRODUCT_DOMAIN_NAME}-env-${ENVIRONMENT_TYPE}/env/terraform.tfstate\" \
                                -backend-config=\"role_arn=arn:aws:iam::${AWS_APPLICATION_ACCOUNT_NUMBER}:role/KopsCrossAccount\"
                            popd
                            '''
                        }
                    }
            }
        }

        stage('TF plan') {
            steps {
                    withCustomEnv() {
                        sshagent(['bitbucket-key']) {
                            sh '''#!/bin/bash -x
                            pushd application/${AWS_REGION}/env

                            terraform plan -out=tfplan -var-file="../terraform.tfvars" -input=false
                            popd
                            '''
                        }
                    }

            }
        }


        stage('TF apply') {
           input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                    withCustomEnv() {
                        sshagent(['bitbucket-key']) {
                            sh '''#!/bin/bash -x
                            pushd application/${AWS_REGION}/env

                            # CREATE:
                            terraform apply -input=false tfplan
                            
                            popd
                            '''
                        }
                    }
                
            }
        }
        

        stage('Collect artifacts') {
            steps {
                    withCustomEnv() {
                        sshagent(['bitbucket-key']) {
                            sh '''#!/bin/bash -x
                            mkdir -p outputs
                            pushd outputs
                            cp -r /home/jenkins/.ssh/ ./
                            mkdir .kube
                            cp /home/jenkins/.kube/config ./kube/app_config
                            popd
                            ls -al outputs
                            #FIXME: consider generating kops state from s3 bucket and storying K8s instances ssh key in SSM to make artifacts immutable
                            '''
                        }
                        archiveArtifacts artifacts: 'outputs/**'
                    }
            
            }
        }
    }
}


void withCustomEnv(List envVars = [],  def body) {
    List proxies =[]
    List envVariables = [
        'GIT_SSH_COMMAND=ssh -o StrictHostKeyChecking=no'
    ]
    withAWSParameterStore(credentialsId: '', namePrefixes: '', naming: 'absolute', path: '/proxy', recursive: true, regionName: "$AWS_REGION") {
        script {
            if (env.PROXY_HTTP) {
                proxies << "http_proxy=$PROXY_HTTP"
            }
            if (env.PROXY_HTTPs) {
                proxies << "https_proxy=$PROXY_HTTPS"
            }
            if (env.PROXY_NO) {
                proxies << "no_proxy=$PROXY_NO"
            }
            envVariables.addAll(proxies)
        }
    }
    envVariables.addAll(envVars)

    withEnv(envVariables) {
        body.call()
    }
}
