pipeline {
    parameters {
        string(name: 'PRODUCT_DOMAIN_NAME', defaultValue: '')
        string(name: 'ENVIRONMENT_NAME', defaultValue: '')
        string(name: 'CONFIG_REPO_URL', defaultValue: '')
        string(name: 'CONFIG_REPO_DIR', defaultValue: '')
        string(name: 'AWS_ACCOUNT_NUMBER', defaultValue: '')
        string(name: 'AWS_REGION', defaultValue: '')
    }
    agent { label 'jenkins-terraform' }
    stages {
        stage('install required software') {
            steps {
                container('terraform') {
                    withCustomEnv() {
                        sh '''#!/bin/bash -x
                        whoami
                        pwd
                        pip install awscli --upgrade
                        
                        wget -O kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
                        chmod +x ./kops
                        mv ./kops /usr/local/bin/
                        
                        yum --disableplugin=fastestmirror install -y jq
                        
                        ls -al /usr/local/bin
                        terraform version
                        aws --version
                        kubectl --client=true version
                        kops version
                        jq --version
                        
                        pushd ${HOME}
                        if [ ! -d .ssh ];
                        then
                            mkdir -p .ssh
                            chmod 700 .ssh
                        fi
                        ls -al .ssh
                        popd
                        '''
                    }
                }
            }
        }
        stage('check AWS identity') {
            steps {
                container('terraform') {
                    withCustomEnv() {
                        sh '''#!/bin/bash -x
                        aws sts get-caller-identity
                        '''
                    }
                }
            }
        }
        
        stage('Git clone') {
            steps {
                container('terraform') {
                    withCustomEnv() {
                        cleanWs()
                        sshagent(['bitbucket-key']) {
                            sh '''#!/bin/bash -x
                            pwd
                            git clone ${CONFIG_REPO_URL}
                            ls -al ${CONFIG_REPO_DIR}
                            '''
                        }
                    }
                }
            }
        }

        stage('TF init') {
            steps {
                container('terraform') {
                    withCustomEnv() {
                        sshagent(['bitbucket-key']) {
                            sh '''#!/bin/bash -x
                            pushd ${CONFIG_REPO_DIR}
                            pushd application/${AWS_REGION}/env
                            terraform init \
                                -backend-config=\"region=${AWS_REGION}\" \
                                -backend-config=\"bucket=tf-state-bootstrap-${AWS_ACCOUNT_NUMBER}-application-${AWS_REGION}\" \
                                -backend-config=\"key=tf/tf-aws-product-domain-${PRODUCT_DOMAIN_NAME}-env-${ENVIRONMENT_TYPE}/env/terraform.tfstate\" \
                                -backend-config=\"role_arn=arn:aws:iam::${AWS_ACCOUNT_NUMBER}:role/KopsCrossAccount\"
                            popd
                            popd
                            '''
                        }
                    }
                }
            }
        }
                            
        stage('TF plan') {
            steps {
                container('terraform') {
                    withCustomEnv() {
                        sshagent(['bitbucket-key']) {
                            sh '''#!/bin/bash -x
                            pushd ${CONFIG_REPO_DIR}
                            pushd application/${AWS_REGION}/env

                            terraform plan -out=tfplan -input=false
                            popd
                            popd
                            '''
                        }
                    }
                }
            }
        }


        stage('TF apply') {
           input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                container('terraform') {
                    withCustomEnv() {
                        sshagent(['bitbucket-key']) {
                            sh '''#!/bin/bash -x
                            pushd ${CONFIG_REPO_DIR}
                            pushd application/${AWS_REGION}/env

                            # CREATE:
                            terraform apply -input=false tfplan
                            
                            # DESTROY:
                            #terraform destroy -auto-approve
                            #kops --state s3://kops-${AWS_ACCOUNT_NUMBER}-${AWS_REGION}-${PRODUCT_DOMAN_NAME}-${ENVIRONMENT_TYPE} delete cluster ${PRODUCT_DOMAIN_NAME}-${ENVIRONMENT_TYPE}.k8s.local --yes

                            popd
                            popd
                            '''
                        }
                    }
                }
            }
        }
        

        stage('Collect artifacts') {
            steps {
                container('terraform') {
                    withCustomEnv() {
                        sshagent(['bitbucket-key']) {
                            sh '''#!/bin/bash -x
                            mkdir -p outputs
                            pushd outputs
                            cp -r /home/jenkins/.ssh/ ./
                            mkdir .kube
                            cp /home/jenkins/.kube/config ./kube/
                            popd
                            ls -al outputs
                            #FIXME: consider generating kops state from s3 bucket and storying K8s instances ssh key in SSM to make artifacts immutable
                            '''
                        }
                        archiveArtifacts artifacts: 'outputs/**'
                    }
                }
            }
        }
    }
}


void withCustomEnv(List envVars = [],  def body) {
    List proxies =[]
    List envVariables = [
        'GIT_SSH_COMMAND=ssh -o StrictHostKeyChecking=no',
        "AWS_REGION=${params.AWS_REGION}", "AWS_ACCOUNT_NUMBER=${params.AWS_ACCOUNT_NUMBER}", 
        "PRODUCT_DOMAIN_NAME=${params.PRODUCT_DOMAIN_NAME}", "ENVIRONMENT_TYPE=${params.ENVIRONMENT_TYPE}",
        "CONFIG_REPO_URL=${params.CONFIG_REPO_URL}", "CONFIG_REPO_DIR=${params.CONFIG_REPO_DIR}"
    ]
    withAWSParameterStore(credentialsId: '', namePrefixes: '', naming: 'absolute', path: '/proxy', recursive: true, regionName: "${params.AWS_REGION}") {
        script {
            if (env.PROXY_HTTP) {
                proxies << "http_proxy=$PROXY_HTTP"
            }
            if (env.PROXY_HTTPs) {
                proxies << "https_proxy=$PROXY_HTTPS"
            }
            if (env.PROXY_NO) {
                proxies << "no_proxy=$PROXY_NO"
            }
            envVariables.addAll(proxies)
        }
    }
    envVariables.addAll(envVars)

    withEnv(envVariables) {
        body.call()
    }
}
